Assignments/array functions
bhs-intro-to-programming/AidanThomaes pull request #9
Opened 2022-10-24 21:54 UTC by AidanThomaes

2022-10-25 02:49 UTC, gigamonkey requested changes
Pyramid isn't quite right. You should look at the test results and see if you can fix it.

2022-10-25 02:49 UTC, gigamonkey commented on assignments/array-functions/code.js
> +      }
I think these brackets are right but they look a bit wonky because of the formatting. You should use the "Format document" feature in the editor to reformat your code so you get used to seeing properly indented code. Later on knowing what code *should* look like will make it easier to see when something is messed up. (Right click in the edit area to get a context menu and find that option.)

2022-10-25 02:49 UTC, gigamonkey commented on assignments/array-functions/code.js
> +  };
I know I haven't made a big deal about where to use and not use semicolons but just for reference they are not needed after the body's of `if`, `else`, `for`, or `while` constructs. They don't do any harm because they just get treated as an empty statement, i.e. one that does nothing. So far the constructs you know that are properly ended with a `;` are assignment and `return`. 

So

```javascript
a = 10;
````
And also the assignment when we are defining a named function so after the closing `}` of the function body:

```javascript
const foo = (n) => {
  return n * 10;
}; // <--- that one is because this whole thing is part of an assignment.
```

But don't worry too much about this. Javascript is very forgiving in this regard.

2022-10-25 02:49 UTC, gigamonkey commented on assignments/array-functions/code.js
> +      list.push(x,y)
Whoops. This isn't quite right. Can you look at the failing tests and see what's going on?

2022-10-26 21:42 UTC, AidanThomaes commented on assignments/array-functions/code.js
> +      list.push(x,y)
@gigamonkey I never ended up finishing the pyramid as I got stuck and we moved on.

2022-11-03 21:37 UTC, merged